---
- name: Kubernetes Cluster Setup
  hosts: all
  become: yes
  tasks:
    - name: Update and install dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'socat']
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

        update_cache: yes

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create keyrings directory
      file: 
        path: /etc/apt/keyrings
        state: directory

    - name: Check if k8s key already exists
      stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: k8skey

    - name: Add k8s key 
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg # allow unprivileged APT programs to read this keyring
      when: not k8skey.stat.exists

    - name: add k8s repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /

    - name: Install Kubernetes components
      apt:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present

        update_cache: yes

    - name: Hold kubelet, kubeadm, and kubectl at current version
      apt:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present

    - name: Ensure swap is off
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Disable swap in fstab

      replace:
        path: /etc/fstab
        regexp: '(^/swap.img)'
        replace: '#\1'

- name: Initialize Kubernetes Control Plane (Master Node)
  hosts: all 
  become: yes
  tasks:
    
    - name: Initialize Kubernetes Master with kubeadm
      shell: kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all
      register: k8s_init_output
      ignore_errors: yes

    - name: Create kube config directory for user
      file:
        path: /home/kube/.kube
        state: directory
        owner: kube
        mode: 0755

    - name: Copy kube config
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

